### PR TITLE
chore(build): add -Dpie build option to create PIE executable

### PR DESCRIPTION
**Pull request by tranzystorekk**
Having the option to build PIE is useful for potential distro consumers. Hopefully you'll find it acceptable to add 😁

### CODE REVIEW

**Comment by rockorager** [comment]
Thanks!

You are everywhere, haha

**Comment by koibtw** [comment]
he literally is lol. i didn't even know you were contributing to this @tranzystorekk

**Comment by tranzystorekk** [comment]
Hmm, I just noticed the merged commit from this PR has disappeared from the main branch, some omission or git slip-up?

**Comment by rockorager** [comment]
Oh it did. Argh...Ok so I have this repo hosted on sr.ht as the origin, and it mirrors to github with a force push...I'm going to remove this workflow and have the origin be github. I'll apply the commit as a patch and get this fixed shortly. Sorry about that.

**Comment by tranzystorekk** [comment]
Ah, I noticed the sourcehut mention in readme, but didn't realize it's the main repo source.

**Comment by rockorager** [comment]
Well, it’s not anymore as of a few minutes ago :)

**Pull request merged**
